language: node_js
node_js:
  - "0.12"
addons:
  apt:
    packages:
    - zookeeperd
after_script:
  - cat coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
after_success:
  - npm run coverage
